### ISSUE TITLE
Stakced symbols: +/- buttons

### ISSUE THREAD

**Issue by ckinkeldey** [tguelenman/PreCall#42]
reduce width
place on upper border of symbol field

**Comment by tguelenman** [comment]
buttons are at the upper border, but triangle symbol field is higher
still ok?
bringing all symbol fields to the same height might be difficult

**Comment by ckinkeldey** [comment]
Please use same height for triangle field than circle field (and let the width deviate)

**Comment by ckinkeldey** [comment]
This should be a better solution:
![Screenshot 2019-04-17 16 01 45](https://user-images.githubusercontent.com/3234376/56293851-365b8900-612a-11e9-9c4d-7f5230bb8439.png)

**Comment by tguelenman** [comment]
i changed the triangle height to fit the circle height. the fields now have the same heights and widths.
