### ISSUE TITLE
Align Headline 

### ISSUE THREAD

**Issue by ckinkeldey** [tguelenman/PreCall#43]
![Screenshot 2019-04-17 16 05 08](https://user-images.githubusercontent.com/3234376/56294333-1bd5df80-612b-11e9-934d-69864339935f.png)

**Comment by tguelenman** [comment]
set all headlines to use the same (lower than before) padding, causing:
-Model quality metrics to be aligned with ORES Human-Centered ...
-Expected classification result to be aligned with the above
-Threshold good / damaging to fit in one line
