### ISSUE TITLE
Threshold: tiny error

### ISSUE THREAD

**Issue by ckinkeldey** [tguelenman/PreCall#45]
Position of handle

![Screenshot 2019-04-17 16 17 54](https://user-images.githubusercontent.com/3234376/56295022-6310a000-612c-11e9-81ba-538458614cf9.png)

**Comment by tguelenman** [comment]
> Position of handle
> 
> ![Screenshot 2019-04-17 16 17 54](https://user-images.githubusercontent.com/3234376/56295022-6310a000-612c-11e9-81ba-538458614cf9.png)

Sorry, am unable to reproduce. What browser are you using?

**Comment by ckinkeldey** [comment]
![Screenshot 2019-04-18 12 07 32](https://user-images.githubusercontent.com/3234376/56353833-9a398c80-61d2-11e9-8ab2-5e0fb2c470da.png)
Less in Chrome

**Comment by ckinkeldey** [comment]
But might be better to draw grey over black line
