### ISSUE TITLE
Radar chart: tiny errors

### ISSUE THREAD

**Issue by ckinkeldey** [tguelenman/PreCall#46]
![Screenshot 2019-04-17 16 20 22](https://user-images.githubusercontent.com/3234376/56295232-bf73bf80-612c-11e9-89c1-37252bc187c6.png)

![Screenshot 2019-04-17 16 20 27](https://user-images.githubusercontent.com/3234376/56295241-c39fdd00-612c-11e9-8300-048c0f28cd8b.png)

**Comment by ckinkeldey** [comment]
(do not exactly align with circle)

**Comment by ckinkeldey** [comment]
OK, upper (vertical) one works with Chrome

**Comment by ckinkeldey** [comment]
But other one (lower right) still slightly overlapping in Chrome

**Comment by tguelenman** [comment]
is it fixed for you now? (at least in Chrome?)

**Comment by ckinkeldey** [comment]
Yep, great
