### ISSUE TITLE
+/- Buttons: highlight on hover

### ISSUE THREAD

**Issue by ckinkeldey** [tguelenman/PreCall#50]
1. color light blue on hover 
![Screenshot 2019-04-18 13 16 51](https://user-images.githubusercontent.com/3234376/56357737-d671ea80-61dc-11e9-950d-0d441c008785.png)

**Comment by ckinkeldey** [comment]
2. grey out if value is already minimum (-) or maximum (+)
(other example)
![Screenshot 2019-04-18 13 22 10](https://user-images.githubusercontent.com/3234376/56357785-015c3e80-61dd-11e9-9dd4-c027c69258a1.png)

**Comment by tguelenman** [comment]
> 1. color light blue on hover
>    ![Screenshot 2019-04-18 13 16 51](https://user-images.githubusercontent.com/3234376/56357737-d671ea80-61dc-11e9-950d-0d441c008785.png)

light blue everywhere or also red on damaging ones?

**Comment by ckinkeldey** [comment]
light grey
